In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('../Computer-Vision-with-Python/DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
labels


array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
X = features
y = labels

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler_object = MinMaxScaler()

In [16]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [17]:
scaled_X_train = scaler_object.transform(X_train)

In [18]:
scaled_X_test = scaler_object.transform(X_test)

In [19]:
# create neural network

In [20]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
model = Sequential()

#input layer

model.add(Dense(4, input_dim=4, activation='relu'))

#hidden layer

model.add(Dense(8, activation='relu'))

#output layre

model.add(Dense(1, activation='sigmoid'))

In [22]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])

In [23]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
 - 1s - loss: 0.6877 - acc: 0.5734
Epoch 2/50
 - 0s - loss: 0.6844 - acc: 0.6094
Epoch 3/50
 - 0s - loss: 0.6786 - acc: 0.6551
Epoch 4/50
 - 0s - loss: 0.6614 - acc: 0.6866
Epoch 5/50
 - 0s - loss: 0.6353 - acc: 0.7943
Epoch 6/50
 - 0s - loss: 0.6087 - acc: 0.8303
Epoch 7/50
 - 0s - loss: 0.5835 - acc: 0.8694
Epoch 8/50
 - 0s - loss: 0.5586 - acc: 0.8814
Epoch 9/50
 - 0s - loss: 0.5329 - acc: 0.8705
Epoch 10/50
 - 0s - loss: 0.5074 - acc: 0.8945
Epoch 11/50
 - 0s - loss: 0.4834 - acc: 0.8857
Epoch 12/50
 - 0s - loss: 0.4609 - acc: 0.8912
Epoch 13/50
 - 0s - loss: 0.4407 - acc: 0.8945
Epoch 14/50
 - 0s - loss: 0.4212 - acc: 0.8988
Epoch 15/50
 - 0s - loss: 0.4041 - acc: 0.8999
Epoch 16/50
 - 0s - loss: 0.3888 - acc: 0.9010
Epoch 17/50
 - 0s - loss: 0.3737 - acc: 0.9042
Epoch 18/50
 - 0s - loss: 0.3598 - acc: 0.9108
Epoch 19/50
 - 0s - loss: 0.3469 - acc: 0.9097
Epoch 20/50
 - 0s - loss: 0.3356 - acc: 0.9086
Epoch 21/50
 - 0s - loss: 0.3239 - acc: 0.9151
Epoch 22/50
 - 0s - lo

In [24]:
model.predict_classes(scaled_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [25]:
model.metrics_names

['loss', 'acc']

In [26]:
from sklearn.metrics import confusion_matrix, classification_report

In [27]:
predictions = model.predict_classes(scaled_X_test)

In [28]:
confusion_matrix(y_test, predictions)

array([[254,   3],
       [ 10, 186]])

In [29]:
print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

        0.0       0.96      0.99      0.98       257
        1.0       0.98      0.95      0.97       196

avg / total       0.97      0.97      0.97       453



In [30]:
model.save('firstmodel.h5')

In [31]:
from keras.models import load_model

In [32]:
newmodel = load_model('firstmodel.h5')

In [33]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    